/*
SQLyog Community v13.1.9 (64 bit)
MySQL - 10.4.25-MariaDB : Database - cardlist
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`cardlist` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `cardlist`;

/*Table structure for table `card` */

DROP TABLE IF EXISTS `card`;

CREATE TABLE `card` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SKU` varchar(50) NOT NULL,
  `name` text DEFAULT NULL,
  `description` mediumblob DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `image` varchar(300) DEFAULT NULL,
  `grade` int(11) DEFAULT NULL,
  `nation` varchar(150) DEFAULT NULL,
  `rarity` varchar(50) DEFAULT NULL,
  `race` varchar(150) DEFAULT NULL,
  `critical` int(11) DEFAULT NULL,
  `illustrator` varchar(250) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `regulation` varchar(50) DEFAULT NULL,
  `shield` int(11) DEFAULT NULL,
  `skill` varchar(50) DEFAULT NULL,
  `trigger_type` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_update` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `card_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `category` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4;

/*Data for the table `card` */

insert  into `card`(`id`,`SKU`,`name`,`description`,`category_id`,`image`,`grade`,`nation`,`rarity`,`race`,`critical`,`illustrator`,`power`,`regulation`,`shield`,`skill`,`trigger_type`,`type`,`create_date`,`last_update`) values 
(1,'D-SD01/001BH','Chakrabarthi Divine Dragon, Nirvana','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Aktif.png\"\" title=\"\"AKT\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_VC.png\"\" title=\"\"[VC]\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_1Giliran.png\"\" title=\"\"1 Giliran\"\">: <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[Buang <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\"> dari tangan], pilih <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\"> grade 0 dari <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Zona_Musnah.png\"\" title=\"\"Zona Musnah\"\"> dan panggil ke <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Lingkaran_RG.png\"\" title=\"\"RC\"\">. <br /><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_VC.png\"\" title=\"\"[VC]\"\"> : Apabila unit ini menyerang, <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[<img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_CounterBlast_1.png\"\" title=\"\"CounterBlast 1\"\">], unit ini dan semua unit anda dengan <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_OverDress.png\"\" title=\"\"OverDress\"\"> dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000 hingga akhir giliran.</div>\n\n<div class=\"\"flavor\"\">Oo Chakrabarthi, bawalah harapan dan terangi dunia.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_001BH.png',3,'Dragon Empire','SD','Flame Dragon',1,'illust / HMK84',13000,'Standard',0,'Twin Drive Persona Ride','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(2,'D-SD01/002BH','Blaze Maiden, Reiyu','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\">: Apabila unit ini diride oleh \"\"Chakrabarthi Divine Dragon, Nirvana\"\", <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[<img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_SoulBlast_1.png\"\" title=\"\"SoulBlast 1\"\">], cari dek anda untuk maksimum satu \"\"Vairina\"\", tunjukkan, letak ke tangan, dan shuffle dek anda. <br /><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_TerusMenerus.png\"\" title=\"\"BTS\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_VC-RC.png\"\" title=\"\"[VC/RC]\"\"> : Dalam pertempuran dimana unit ini menyerang, unit ini dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +2000.</div>\n<div class=\"\"flavor\"\">Rino! Jangan takutkan telur itu!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_002BH.png',2,'Dragon Empire','SD','Human',1,'design / 伊藤彰　illust / 獣道',10000,'Standard',5000,'Intercept','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(3,'D-SD01/003BH','Blaze Maiden, Rino','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\">: Apabila unit ini diride oleh \"\"Blaze Maiden, Reiyu\"\", cari dek anda untuk maksimum satu \"\"Trickstar\"\", panggil ke <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Lingkaran_RG.png\"\" title=\"\"RC\"\">, dan shuffle dek anda. <br /><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_TerusMenerus.png\"\" title=\"\"BTS\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_VC-RC.png\"\" title=\"\"[VC/RC]\"\"> : Dalam pertempuran di mana unit ini menyerang, unit ini dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +2000.</div>\n\n<div class=\"\"flavor\"\">Harapan kita pasti akan tercapai!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_003BH.png',1,'Dragon Empire','SD','Human',1,'illust / 麻谷知世',8000,'Standard',5000,'Boost','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(4,'D-SD01/004BH','Sunrise Egg','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\">: Apabila unit ini diride, jika anda pemain kedua, draw <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\">.</div>\n<div class=\"\"flavor\"\">Telur yang membawa sinar harapan.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_004BH.png',0,'Dragon Empire','SD','Flame Dragon',1,'illust / ひと和',6000,'Standard',5000,'Boost','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(5,'D-SD01/005BH','Fire Slash Dragon, Inferno Sword','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_TerusMenerus.png\"\" title=\"\"BTS\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_RC.png\"\" title=\"\"[RC]\"\">  : Dalam pertempuran dimana unit ini menyerang, unit ini dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +2000.</div>\n<div class=\"\"flavor\"\">Api yang akan memusnahkan segalanya.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_005BH.png',3,'Dragon Empire','SD','Flame Dragon',1,'illust / 竜徹',13000,'Standard',0,'Twin Drive Persona Ride','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(6,'D-SD01/006BH','Vairina','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_OverDress.png\"\" title=\"\"OverDress\"\"> - \"\"Trickstar\"\" (Anda boleh letak unit ini keatas unit yang ditentukan daripada panggil seperti unit normal ke <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Lingkaran_RG.png\"\" title=\"\"RC\"\">)<br /><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_RC.png\"\" title=\"\"[RC]\"\">  : Apabila unit ini menyerang Vanguard dalam kondisi <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_OverDress.png\"\" title=\"\"OverDress\"\">, unit ini dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000  hingga akhir pertempuran. Kemudian, <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[<img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_SoulBlast_2.png\"\" title=\"\"SoulBlast 2\"\">], pilih salah satu unit RG pihak lawan dan gugurkan.</div>\n\n<div class=\"\"flavor\"\">Penjelmaan baru yang muncul dari harapan.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_006BH.png',2,'Dragon Empire','SD','Talisman',1,'illust / 萩谷薫',10000,'Standard',5000,'Intercept','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(7,'D-SD01/007BH','Iron Ball Dragon, Ankybowler','\"<div class=\"\"effect\"\">-</div>\n<div class=\"\"flavor\"\">Berat dan melaju dengan cepat, tidak dapat dihentikan!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_007BH.png',1,'Dragon Empire','SD','Dinodragon',1,'illust / ひと和',8000,'Standard',5000,'Boost','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(8,'D-SD01/008BH','Escort Stealth Dragon, Hayashi Kaze','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_TerusMenerus.png\"\" title=\"\"BTS\"\">: Sentinel (Anda hanya boleh mempunyai maksimum <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_4.png\"\" title=\"\"4 Kartu\"\"> dengan \"\"Sentinel\"\" di dalam dek.)<br /><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_Auto.png\"\" title=\"\"Auto\"\">: Apabila unit ini diletak ke <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Lingkaran_Guard.png\"\" title=\"\"GC\"\">, <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[buang <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\"> dari tangan], pilih salah satu unit anda, unit itu dapat pertahanan sempurna hingga akhir pertempuran.</div>\n\n<div class=\"\"flavor\"\">Tanpa sebarang cela, pertahanan sempurna!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_008BH.png',1,'Dragon Empire','SD','Abyss Dragon',1,'design / 伊藤彰　illust / 前河悠一',7000,'Standard',0,'Boost','Sentinel','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(9,'D-SD01/009BH','Trickstar','\"<div class=\"\"effect\"\"><img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kemampuan_TerusMenerus.png\"\" title=\"\"BTS\"\"> <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_RC.png\"\" title=\"\"[RC]\"\">  : Unit ini tidak boleh dipilih oleh efek <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu.png\"\" title=\"\"Kartu\"\"> pihak lawan.</div>\n<div class=\"\"flavor\"\">Menarik! Mari kita bermain bersama!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_009BH.png',0,'Dragon Empire','SD','Talisman',1,'design / 伊藤彰　illust / 獣道',5000,'Standard',5000,'Boost','','Normal','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(10,'D-SD01/010BH','Spiritual King of Determination, Olbaria','\"<div class=\"\"effect\"\">(Anda hanya boleh mempunyai maksimum satu unit <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Trigger_OverTrigger.png\"\" title=\"\"Overtrigger\"\"> di dalam dek. Apabila ditunjukkan sebagai trigger, hapuskan <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu.png\"\" title=\"\"Kartu\"\"> ini, draw <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\">, pilih salah satu unit anda, dan unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +100 Juta hingga akhir giliran! Jika ditunjukkan semasa drive cek, dapatkan efek tambahan!)<br />Efek tambahan - Pilih salah satu unit anda, dan unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +100 Juta hingga akhir giliran!</div>\n<div class=\"\"flavor\"\">Kunci keajaiban adalah harapan dan jiwa yang membara!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_010BH.png',0,'','SD','Elemental',1,'illust / 麻谷知世',5000,'Standard',50000,'Boost','Over','Trigger','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(11,'D-SD01/011BH','Blaze Maiden, Zonne','\"<div class=\"\"effect\"\">(Apabila ditunjukkan sebagai trigger, pilih salah satu unit anda, unit itu dapat  <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kritikal.png\"\" title=\"\"Kritikal\"\"> +1 hingga akhir giliran! Kemudian, pilih salah satu unit anda, unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000 hingga akhir giliran!)</div>\n<div class=\"\"flavor\"\">\"\"Red Dawn Manor\"\" tanah harapan sejak era mitos.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_011BH.png',0,'Dragon Empire','SD','Human',1,'illust / ひと和',5000,'Standard',15000,'Boost','Kritikal','Trigger','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(12,'D-SD01/012BH','Blaze Staff Monk, Cho Kuu Sha','\"<div class=\"\"effect\"\">(Apabila ditunjukkan sebagai trigger, draw <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu_1.png\"\" title=\"\"1 Kartu\"\">! Kemudian, pilih salah satu unit anda, unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000 hingga akhir giliran!)</div>\n<div class=\"\"flavor\"\">Saat harapan menjadi kenyataan.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_012BH.png',0,'Dragon Empire','SD','Human',1,'illust / 竜徹',5000,'Standard',5000,'Boost','Draw','Trigger','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(13,'D-SD01/013BH','Blaze Fist Monk, Nikko','\"<div class=\"\"effect\"\">(Apabila ditunjukkan sebagai trigger, semua unit anda di baris depan dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000 hingga akhir giliran!)</div>\n<div class=\"\"flavor\"\">Kemunculan dunia baru, itulah \"\"Red Dawn Manor\"\".</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_013BH.png',0,'Dragon Empire','SD','Human',1,'illust / 萩谷薫',5000,'Standard',15000,'Boost','Front','Trigger','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(14,'D-SD01/014BH','Blaze Maiden, Rona','\"<div class=\"\"effect\"\">(Anda hanya boleh mempunyai maksimum empat unit <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Trigger_Heal.png\"\" title=\"\"Heal\"\"> di dalam dek. Apabila ditunjukkan sebagai trigger, pilih salah satu unit anda, unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +10000 hingga akhir giliran! Kemudian, jika jumlah <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu.png\"\" title=\"\"Kartu\"\"> di <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Zona_Luka.png\"\" title=\"\"Zona Luka\"\"> anda lebih atau sama dengan pihak lawan, sembuhkan!)</div>\n<div class=\"\"flavor\"\">\"\"Blaze Maiden\"\" penuh dengan cahaya harapan.</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_014BH.png',0,'Dragon Empire','SD','Human',1,'illust / ひと和',5000,'Standard',15000,'Boost','Heal','Trigger','2022-10-21 16:40:52','2022-10-21 16:40:52'),
(15,'D-SD01/015BH','Sunburst Evolution','\"<div class=\"\"effect\"\">Mainkan <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kartu.png\"\" title=\"\"Kartu\"\"> ini dengan <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_KOS.png\"\" title=\"\"Kos\"\">[<img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_CounterBlast_1.png\"\" title=\"\"CounterBlast 1\"\">]!<br />\nPilih salah satu unit anda, unit itu dapat <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Kuasa.png\"\" title=\"\"Kuasa\"\"> +5000 hingga akhir giliran. Pilih satu \"\"Vairina\"\" dari <img src=\"\"https://cf-vanguard.id/wp-content/uploads/2022/10/Icon_Zona_Musnah.png\"\" title=\"\"Zona Musnah\"\"> anda dan letak ke dalam tangan.</div>\n<div class=\"\"flavor\"\">Teruskan perjuangan ini dengan semangat yang membara!</div>\"',1,'https://cf-vanguard.id/wp-content/uploads/2022/08/D_SD01_015BH.png',2,'Dragon Empire','SD','',0,'design / 伊藤彰　illust / 前河悠一',0,'Standard',0,'','Normal','Order','2022-10-21 16:40:52','2022-10-21 16:40:52');

/*Table structure for table `category` */

DROP TABLE IF EXISTS `category`;

CREATE TABLE `category` (
  `category_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(250) DEFAULT NULL,
  `create_date` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_update` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

/*Data for the table `category` */

insert  into `category`(`category_id`,`name`,`description`,`create_date`,`last_update`) values 
(1,'VGB-D-SD01','Starter Dek 01: Yu-yu Kondo - Naga Suci -\r','2022-10-21 13:43:50','2022-10-21 13:43:50');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
